// Banco de palavras para geração de poemas
// Word bank for poem generation

const poetryWords = {
  pt: {
    amor: [
      'coração',
      'paixão',
      'carinho',
      'ternura',
      'afeto',
      'romance',
      'sentimento',
      'abraço',
      'beijo',
      'saudade',
      'encontro',
      'alma',
      'eternidade',
      'felicidade',
      'sonho',
      'desejo',
      'esperança'
    ],
    natureza: [
      'sol',
      'lua',
      'estrelas',
      'céu',
      'mar',
      'montanha',
      'floresta',
      'flores',
      'vento',
      'chuva',
      'aurora',
      'anoitecer',
      'primavera',
      'outono',
      'inverno',
      'verão',
      'jardim',
      'rio',
      'lago'
    ],
    vida: [
      'tempo',
      'memória',
      'juventude',
      'idade',
      'nascimento',
      'crescimento',
      'experiência',
      'sabedoria',
      'jornada',
      'caminho',
      'destino',
      'futuro',
      'presente',
      'passado',
      'momentos',
      'anos',
      'dias'
    ],
    sentimentos: [
      'alegria',
      'tristeza',
      'melancolia',
      'nostalgia',
      'paz',
      'serenidade',
      'angústia',
      'liberdade',
      'solidão',
      'companhia',
      'amizade',
      'família',
      'coragem',
      'medo',
      'confiança',
      'dúvida',
      'certeza'
    ]
  },
  en: {
    love: [
      'heart',
      'passion',
      'affection',
      'tenderness',
      'romance',
      'feeling',
      'embrace',
      'kiss',
      'longing',
      'meeting',
      'soul',
      'eternity',
      'happiness',
      'dream',
      'desire',
      'hope',
      'devotion'
    ],
    nature: [
      'sun',
      'moon',
      'stars',
      'sky',
      'sea',
      'mountain',
      'forest',
      'flowers',
      'wind',
      'rain',
      'dawn',
      'sunset',
      'spring',
      'autumn',
      'winter',
      'summer',
      'garden',
      'river',
      'lake'
    ],
    life: [
      'time',
      'memory',
      'youth',
      'age',
      'birth',
      'growth',
      'experience',
      'wisdom',
      'journey',
      'path',
      'destiny',
      'future',
      'present',
      'past',
      'moments',
      'years',
      'days'
    ],
    feelings: [
      'joy',
      'sadness',
      'melancholy',
      'nostalgia',
      'peace',
      'serenity',
      'anguish',
      'freedom',
      'loneliness',
      'company',
      'friendship',
      'family',
      'courage',
      'fear',
      'confidence',
      'doubt',
      'certainty'
    ]
  }
}

module.exports = poetryWords
